version: '3'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: '3ICok1za'
      MYSQL_DATABASE: 'apertura'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'nk9Nx9pT'
    volumes:
      - 'db-volume:/var/lib/mysql'
    ports:
      - '9906:3306'
    restart: 'always'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'
      - '--general-log=1'
      - '--general-log-file=/custom_sql_log/mysql_query.log'
    build:
      context: '.'
      dockerfile: 'db/Dockerfile'
  web:
    depends_on:
      - 'db'
    ports:
      - '80:3000'
    restart: 'always'
    stdin_open: true
    tty: true
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/productionweb/web/Dockerfile'
volumes:
  db-volume: ~
